name: Check for console.log statements

on:
  pull_request:
    branches:
      - main  # Or the default branch of your repo
    paths:
      - '**/*.js'  # Or any file pattern you want to check

jobs:
  check-console-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for console.log statements
      run: |
        # Find all files with console.log statements and exit with an error if any are found
        if grep -r "console\.log" --include="*.js" .; then
          echo "ERROR: Found console.log statements in the code!"
          exit 1
        else
          echo "No console.log statements found."
        fi
