name: Check for console.log statements

on:
  pull_request:
    branches:
      - main  # Replace with your default branch if needed
    paths:
      - '**/*.js'  # Check JavaScript files
      - '**/*.jsx' # Check JSX files

jobs:
  check-console-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for console.log statements in JS and JSX
      run: |
        # Find all console.log statements in JS and JSX files
        if grep -r "console\.log" --include="*.{js,jsx}" .; then
          echo "ERROR: Found console.log statements in the code!"
          exit 1  # This will cause the workflow to fail
        else
          echo "No console.log statements found."
        fi
